# To Use That run fastlane android `lane_name` => fastlane android firebase_distribution .
default_platform(:android)

platform :android do
  # For develper not display to anyone.
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
    # To clean the build and make a new one before make a new release to add to firebase_app_distribution(...)
    # sh is short for shell command
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      # From Firebase or firebase.json in your project root after adding `Firebase CLI`.
      app: "1:884134719783:android:2697e0adf9830db8aff902",
      # From firebase login:ci after logging in and setting up in android file.
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      # From firebase Docs.
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      # Add new testers by -> ,"new_tester_email"
      testers: "ahmedkattab868@gmail.com",
      release_notes: "For Testing purposes" 
    )
  end
end
